import { WindowInfo } from "./ui_utils.slint";
import { AppText } from "./controls/generic.slint";
import { AboutSlint, Palette } from "std-widgets.slint";

component AboutFelgo {
    width: 100%;
    height: 100%;

    VerticalLayout {
        spacing: 5px;

        width: 90% * parent.width;
        padding-bottom: 15px;

        Rectangle {
            background: Palette.color-scheme == ColorScheme.dark ? white : #151d21;
            border-radius: self.height / 2;

            preferred-height: self.width * 45%;

            logo-layout := VerticalLayout {
                alignment: center;
                spacing: 2px;

                made-text := Text {
                    horizontal-alignment: center;
                    color: Palette.color-scheme == ColorScheme.dark ? #151d21 : white;
                    font-size: 12px;
                    text: "MADE BY";
                }

                Rectangle {
                    Image {
                        image-fit: contain;
                        width: 70% * parent.width;
                        source: Palette.color-scheme == ColorScheme.dark ? @image-url("./assets/felgo-logo_dark.svg")
                                                                         : @image-url("./assets/felgo-logo_light.svg");
                    }
                }
            }
        }

        Text {
            horizontal-alignment: center;
            font-size: 12px;
            color: Palette.color-scheme == ColorScheme.dark ? white : black;
            text: "https://felgo.com/";
        }
    }
}

export component AboutBox {
    VerticalLayout {
        if WindowInfo.is-portrait: VerticalLayout {
            alignment: center;

            Rectangle {
                AboutFelgo {
                    width: Math.min(200px, 80% * parent.width);
                    min-height: self.preferred-height;
                }
            }
            Rectangle {
                AboutSlint {
                    width: Math.min(200px, 80% * parent.width);
                    min-height: self.preferred-height;
                }
            }
        }

        if !WindowInfo.is-portrait: HorizontalLayout {
            alignment: space-around;

            // adjust AboutFelgo size to look the same as AboutSlint
            Rectangle {
                max-width: 200px;

                AboutFelgo {
                    height: 84%;
                    preferred-width: 200px;
                    padding-bottom: 10px;
                }
            }
            
            AboutSlint {
                max-width: 200px;
            }
        }
    }
}
